#ifndef VALUES
#define VALUES

#define CASES_HAUTEUR   (5*2+1)
#define CASES_LARGEUR   (10*2+1)
#define COTE_CASE       20
#define HAUTEUR_CASE    COTE_CASE
#define LARGEUR_CASE    COTE_CASE
#define LARGEUR_TERRAIN CASES_LARGEUR*LARGEUR_CASE
#define HAUTEUR_TERRAIN CASES_HAUTEUR*HAUTEUR_CASE

#define TEMPS_FEU       300

enum direction  { HAUT, BAS, GAUCHE, DROITE, AUCUNE };
enum square  { FIRE, MUR, MUR_DESTRUCTIBLE, RAPIDE, PUISSANCE, BOMBE_SUPPLEMENTAIRE, DETONATEUR, VIDE };

#endif
